name: Build and Push Docker Image
on:
  push:
    branches:
      - master

env:
  KUBERNETES_VERSION: "1.23.5"
  KIND_VERSION: "0.16.0"

jobs:
  build-and-push:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Printing Tag
        run: echo ${{ github.sha }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: whyxn/go-temporal-skeleton:${{ github.sha }}