name: Build and Push
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set environment variables based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref_name }}" =~ "v*" ]]; then
            echo "DOCKER_USERNAME=${{ secrets.PRODUCTION_DOCKER_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{ secrets.PRODUCTION_DOCKER_PASSWORD }}" >> $GITHUB_ENV
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
            
            if [[ "${{ github.ref_name }}" =~ "v*" ]]; then
              echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            fi
          
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "DOCKER_USERNAME=${{ secrets.STAGING_DOCKER_USERNAME }}" >> $GITHUB_ENV
            echo "DOCKER_PASSWORD=${{ secrets.STAGING_DOCKER_PASSWORD }}" >> $GITHUB_ENV
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi
      - name: Printing Tag
        run: echo ${{ env.IMAGE_TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: whyxn/go-temporal-skeleton:${{ env.IMAGE_TAG }}