name: Build and Push Docker Image
on:
  push:
    branches:
      - master

env:
  KUBERNETES_VERSION: "1.23.5"
  KIND_VERSION: "0.16.0"

jobs:
  build-and-push:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: whyxn/go-temporal-skeleton:${{ github.sha }}

  deploy:
    if: github.event_name == 'workflow_dispatch'
    needs: build-and-push
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl"
          sudo install ./kubectl /usr/local/bin/ && rm kubectl
          kubectl version --short --client
          kubectl version --short --client | grep -q ${KUBERNETES_VERSION}
      - name: Install Kind
        run: |
          curl -L -o kind https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64
          sudo install ./kind /usr/local/bin && rm kind
          kind version
          kind version | grep -q ${KIND_VERSION}
      - name: Create Kind Cluster
        run: |
          kind create cluster
      - name: Set up Cluster
        run: |
          kubectl cluster-info
          kubectl get no
      - name: Check Nodes
        run: |
          kubectl get no
      - name: Wait for Kind Cluster to be Ready
        run: sleep 30s
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.2
      - name: Deploy
        run: |
          kubectl create ns test
          helm upgrade --install gts ./helm/go-temporal-skeleton \
            --set image.tag=${{ github.sha }} \
            --namespace test
        shell: bash
      - name: Check Rollout Status
        run: kubectl rollout status deploy/gts-go-temporal-skeleton -n test
