name: Deploy
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The Tag to deploy'
        required: true

env:
  KUBERNETES_VERSION: "1.23.5"
  KIND_VERSION: "0.16.0"

jobs:
  admin_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is an admin
        id: admin_check
        env:
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          user_login=${{ github.actor }}
          is_admin=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$REPOSITORY/collaborators/$user_login/permission" | jq -r '.permission')
          if [ "$is_admin" != "admin" ]; then
            echo "error: Only repository admins can trigger this workflow."
            exit 1
          else
            echo "User is an admin. Proceeding with the workflow."
          fi

  deploy:
    name: ${{ format('Deploy - {0}', github.event.inputs.tag) }}
    needs: admin_check
    if: github.event_name == 'workflow_dispatch'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Printing Tag
        run: echo ${{ inputs.tag }}
      - name: Set up kubectl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Set up context
        run: |
          doctl kubernetes cluster kubeconfig save ${{ secrets.DO_CLUSTER_NAME }} --expiry-seconds=180
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.2
      - name: Create Namespace
        run: kubectl create ns ${{ vars.DO_NAMESPACE }}
        continue-on-error: true
      - name: Deploy
        run: |
          helm upgrade --install gts ./helm/go-temporal-skeleton \
            --set image.tag=${{ inputs.tag }} \
            --namespace ${{ vars.DO_NAMESPACE }}
        shell: bash
      - name: Check Rollout Status
        run: kubectl rollout status deploy/gts-go-temporal-skeleton -n ${{ vars.DO_NAMESPACE }}
